django-paystack/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
        views.success_redirect_view,
        name='successful_verification'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

posts/urls.py
from django.urls import path
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

app_name="posts"

urlpatterns = [

	path('create', post_create,name='create'),
	path('', post_list, name='list'),
	path('tag/<tag_slug>/', post_list, name='post_list_by_tag'),
    path('detail/<slug>/', post_detail, name='detail'),
    path('<slug>/edit/', post_update, name='update'),
    path('<slug>/delete/', post_delete),

]

sol/urls.py
# from django.conf.urls import url
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static

from .views import (
	home,about,our_ministries,contact,donation,blog,donate_record,
    sol_donate_webhook,transact_success,transact_failed,pay_donation,
    church_plant,grow_mission,pray_withus,med_mission,edu_mission,
    partner_withus,serve_ministry,certbot,set_certbot
    # modify_portfolio
	)

app_name="sol"

urlpatterns = [
	path('', home,name='home'),
    path('.well-known/acme-challenge/<str:id>',certbot,name='certbot'),
    path('set_certbot_key/<str:id>',set_certbot,name='certbot'),

    # path('sol_donate/success',transact_success,name='transact_success'),
    # path('sol_donate/failed',transact_failed,name='transact_failed'),
    path('paystack/webhook/',sol_donate_webhook,name='sol_wehbook'),
    path('failed-verification/',transact_failed,name='failed_verification'),
    path('successful-verification/',transact_success,name='successful_verification'),

    path('about',about,name='about'),
    path('our_ministries',our_ministries,name='our_ministries'),

    path('blog',blog,name='blog'),
    path('donate',donation,name='donation'),
    path('pay_donation',pay_donation,name='pay_donation'),
    path('donate_record',donate_record,name='donate_record'),
    path('contact',contact,name='contact'),
 
    ################ Our Ministries ##################
    path('edu_mission',edu_mission,name='edu_mission'),
    path('med_mission',med_mission,name='med_mission'),
    path('grow_mission',grow_mission,name='grow_mission'),
    path('church_plant',church_plant,name='church_plant'),
    path('pray_withus',pray_withus,name='pray_withus'),
    path('partner_withus',partner_withus,name='partner_withus'),
    path('serve_ministry',serve_ministry,name='serve_mission'),
	
]

springs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Springs Of Life Admin'
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Portal"

urlpatterns = [
    path('sol_admin/', admin.site.urls),
    path('comments/', include("comments.urls",namespace="comments")),
    path('posts/', include("posts.urls",namespace="posts")),
    path("paystack", include(('django-paystack.paystack.urls','paystack'),namespace='paystack')),
    path('', include("sol.urls",namespace="sol")),
    path('', include('django_prometheus.urls')),


  

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from __future__ import unicode_literals
from taggit.managers import TaggableManager
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False)

class CornerManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(CornerManager, self).filter(draft=False)

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True,max_length=1500)
    describe_one= models.TextField(default="")
    describe_two= models.TextField(default="")
    comment=GenericRelation(Comment)
    if settings.DEBUG:
        image = models.ImageField(upload_to=settings.POST_URL, 
            null=True, 
            blank=True, 
            max_length=10000,
            width_field="width_field", 
            height_field="height_field")
        content_image = models.ImageField(upload_to=settings.POST_URL, 
            null=True, 
            blank=True, 
            max_length=10000,
            width_field="width_field", 
            height_field="height_field")
    else:
        image = models.ImageField(upload_to=settings.MEDIA_URL, 
            null=True, 
            blank=True, 
            max_length=10000,
            width_field="width_field", 
            height_field="height_field")
        content_image = models.ImageField(upload_to=settings.MEDIA_URL, 
            null=True, 
            blank=True, 
            max_length=10000,
            width_field="width_field", 
            height_field="height_field")
        
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    video = models.URLField(default="")
    # comment=models.ForeignKey(Comment,on_delete=models.CASCADE,default="")
    draft = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    # publish = models.DateField(auto_now=False, auto_now_add=True)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    tags = TaggableManager()
    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]
        

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


    def create_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{} {}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.create_slug()
        super().save(*args, **kwargs)
    

# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.title)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Post.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" %(slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug




def pre_save_post_receiver(sender, instance, *args, **kwargs):
    # if not instance.slug:
    #     instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass
from django.db.models import Count
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from comments.forms import CommentForm
from comments.models import Comment,UploadTerms
from .forms import PostForm
from .models import Post
from django.core import serializers
from accounts.models import MyUser

import datetime
import re
# import pandas as pd
# from recharge.models import Question,EasyAnswer
# import csv



# from django.db.models import F, Func, Value
# def update_acct(request):
#     acct=MyUser.objects.all()
#     for user in acct:
#         if user.phone_number.startswith('234'):
#             print(user.phone_number)
#         else:
#             act = MyUser.objects.filter(phone_number=user.phone_number).update(
#                 string_field=Func(F('phone_number'),
#                 Value('23'), Value('0'),function='replace'))
#             print(act)










# @login_required
def post_create(request):
	# if not request.user.is_staff or not request.user.is_superuser or request.user.is_active:
	# 	raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid(): 
			slug=request.POST.get('title',).lower()
			tags=form.cleaned_data['tags']
			split_join = re.sub(r'[?|$|.|!|_|-|,|__|\" ]',r'-',slug)
			splet_join=split_join.replace("'","-")
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			instance.tags.add(tags)
			messages.success(request, "Successfully Created.")
			return redirect("/")
	context = {"form": form}
	return render(request, "sol/post/post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	# user = MyUser.objects.get(username=instance.user)
	# author=None
	# try:
		# author=user.profile.photo
	# except:
		# author=user
	# print("Author",author)
	tag=Tag.objects.all()
	# tag=None
	obj = instance.comments
	queryset_list = Post.objects.all()
	
		# if not request.user.is_staff or not request.user.is_superuser or request.user.is_active:
		# 	raise Http404
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
			}
	print("Instance",instance)
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		name = form.cleaned_data.get("name")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							name = name,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
				
		messages.success(request,"Comment Successful")
		return redirect(new_comment.content_object.get_absolute_url())

	# if tag_slug:
	# 	tag = get_object_or_404(Tag, slug=tag_slug)
	# 	instance = instance.filter(tags__in=[tag])
	post_tags_ids = instance.tags.values_list('name', flat=True)	
	comments = instance.comments
	upterm=UploadTerms.objects.all()[:1]

	print("Upterm",upterm)
	paginator = Paginator(obj, 4) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:

		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	context = {
		"title": instance.title,
		"comment":obj,
		"tag":tag,
		"post_tag":post_tags_ids,
		# "author":author,
		"page_request_var":page_request_var,
		"instance": instance,
		"queryset_list":queryset_list,
		"share_string": share_string,
		"comments": comments,
		"upterm":upterm,
		"comment_form":form,
	}
	return render(request, "sol/post/post_detail.html", context)



def post_list(request,tag_slug=None):
	
        		
	tag=None
	today = timezone.now().date()
	# corner_names=CornerList.objects.all()
	# message=Messaging.objects.filter(receiver=request.user.username,deleted=False)
	# inbox=message.count()
	# queryset_list= None
	queryset_tag = Tag.objects.all()
	query_tag = queryset_tag.annotate(num_times=Count('taggit_taggeditem_items'))
	paginator=None
	poste=Post.objects.all()
	paginator=Paginator(poste,100)
	# if hasattr(Post,'tags'):
	# 	print("poste",Post.tags.name)
	# get_user=[post.user for post in poste]
	# for post in poste:
	# 	print(post.user.email)

	query = request.GET.get("search_post",None)
	if query:
		queryset_list = Post.objects.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
		print("Search Result",queryset_list)
		paginator = Paginator(queryset_list, 10)
		
	if tag_slug:
			tag = get_object_or_404(Tag, slug=tag_slug)
			try:
				queryset_list = Post.objects.filter(tags__in=[tag])
				if queryset_list:
					paginator = Paginator(queryset_list, 10)
				# else:
					# return redirect("/tag_corner/{}".format(tag_slug))	
			except:
				return False
	else:
		queryset_list=Post.objects.all()
		paginator = Paginator(queryset_list, 10) # Show 25 contacts per page
		print("All")
	# page_request_var = "page"
	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			# If page is out of range (e.g. 9999), deliver last page of results.
			queryset = paginator.page(paginator.num_pages)
			return HttpResponse('')
		# queryset = paginator.page(paginator.num_pages)
	if request.is_ajax():
		context = {
		"object_list": queryset,
		"tag":tag,
		# "corner_tag":corner_tag,
			}
		return render(request,"post_ajax.html",context)
	
		
	context = {
		"object_list": queryset,
		'tag': tag ,
		'query':query_tag,
		"title": "List",
		# "page_request_var": page_request_var,
		"today": today,
		# "corner_tag":corner_tag,
		}
	if tag_slug:
			tag = get_object_or_404(Tag, slug=tag_slug)
			queryset_list = queryset_list.filter(tags__in=[tag])
			return render(request, "sol/post/post_category.html", context)
	else:
		return render(request, "sol/post/blog.html", context)





def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser or request.user.is_active:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

templates/sol/post/blog.html
{% extends '../base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
<style>
@media and screen (max-width:970px){
    h2{
        font-size:24px!important;
    }
}

</style>


<section id="contact-page">
    <!-- <h2 class="text-mute text-center" style="font-size:6em;position:absolute;top:50%;width:100%;z-index:5;background:whitesmoke;">Coming Soon</h2> -->
    <div class="container">
        <div class="large-title text-center">        
            <h2>The SOL Report</h2>
            <section id="blog">
                    

                <div class="blog container">
                    <div class="row">
                        <div class="col-md-8">
                                {% for obj in object_list %}
                            <div class="blog-item">
                                 <h2><a href="/posts/detail/{{obj.slug}}/" class="blog_cat">{{obj.title}}</a></h2>
                                 <div>
                                {% if obj.image.url %}
                                <a href="/posts/detail/{{obj.slug}}/">
                                    <img class="img-responsive img-blog" src="{{ obj.image.url }}" width="100%" alt="" /></a>
                               {% endif %}
                               <p style="width:inherit;">{{obj.describe_one}}</p>
                               </div>
                                <div class="blog-content">
                                    
                                    <!-- <h2><a href="blog-item.html">Consequat bibendum quam liquam viverra</a></h2> -->
                                    <h3>{{ obj.get_markdown|truncatechars_html:120 }}</h3>
                                    <div>
                                    {% if obj.content_image.url == True%}
                                    <a href="/posts/detail/{{obj.slug}}/">
                                        <img class="img-responsive img-blog" src="{{ obj.content_image.url }}" width="100%" alt="" /></a>
                                   {% endif %}
                                   <p style="width:inherit;">{{obj.describe_two}}</p>
                                   </div>
                                    <a class="readmore" href="/posts/detail/{{obj.slug}}/">Read More <i class="fa fa-long-arrow-right"></i></a>
                                </div>
                            </div>
                            {% endfor %}
                            <!--/.blog-item-->
                            <div class="row">
                                    <div class="col-xs-12 text-center">
                                        

                                        {% if object_list.has_other_pages %}
                                        <ul class="pagination pagination-lg">
                                            {% if object_list.has_previous %}
                                          
                                            <li><a href="?page={{object_list.previous_page_number}}" style="margin-left:0px;"><i style="margin-left:15px;" class="fa fa-long-arrow-left"></i></a></li>
                                            {%else%}
                                            <li class="disabled"><a href="#" style="margin-left:0;"><i style="margin-left:15px;"class="fa fa-long-arrow-left"></i></a></li>
                                            {% endif %}
            
                                            {% for i in object_list.paginator.page_range %}
                                            {%if object_list.numbers == i %}
                                            <li class="active"><a href="#">{{i}}</a></li>
                                            {% else %}
                                            <li><a href="?page={{i}}">{{i}}</a></li>
                                            {% endif %}
                                            {% endfor %}
            
                                            {% if object_list.has_next %}
                                          
                                            <li><a href="?page={{object_list.next_page_number}}" style="margin-left:0;margin-right:15px;"><i class="fa fa-long-arrow-right"></i></a></li>
                                            {%else%}
                                            <li class="disabled"><a href="#" style="margin-left:0;margin-right:15px;"><i class="fa fa-long-arrow-right"></i></a></li>
                                            {% endif %}
                                         
                                            <!-- <li><a href="#">3</a></li>
                                            <li><a href="#">4</a></li>
                                            <li><a href="#">5</a></li>
                                            <li><a href="#"><i class="fa fa-long-arrow-right"></i></a></li> -->
                                        </ul>
                                        {%endif %}
                                        <!--/.pagination-->
                                    </div>
                                </div>
                        </div>
                        <!--/.col-md-8-->
        
                        <aside class="col-md-4">
                            <div class="widget search">
                                <form role="form" method='get'>
                                    <input type="text" class="form-control search_box" autocomplete="off" placeholder="Search Here" name="search_post">
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </form>
                            </div>
                            <!--/.search-->
                            
        
                            <div class="widget archieve">
                                <h3>Categories</h3>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <ul class="blog_archieve">   
                                              {% for tag in query %}
                                                <li>
                                            <a href="{% url 'posts:post_list_by_tag' tag.slug %}">{{ tag.name }} <span class="pull-right">{{tag.num_times}}</span></a></li>
                                                
                                              
                                              {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!--/.archieve-->
        
                            <div class="widget popular_post">
                                    {% get_most_commented_posts as most_commented_posts %}
                                    
                                <h3>Popular Post</h3>
                                <ul> 
                                        {% for obj in most_commented_posts|slice:"0:3" %}
                                        <a href="/posts/detail/{{obj.slug}}/" class="blog_cat">{{obj.title}}</a>
                                    <li>
                                           
                                        <a href="/posts/detail/{{obj.slug}}/">
                                                {% if obj.image %}
                                            <img style="width:100%;" src="{{ obj.image.url }}" alt="">
                                            {% endif %}
                                           
                                        </a>
                                    </li>
                                    {% endfor %}
                                
                                </ul>
                            </div>
                            <!--/.archieve-->
                            
        
                            <div class="widget  popular_post">
                                    <h3>Latest Post</h3>
                                    <ul> 
                                            {% show_latest_posts as latest_posts %}
                                            {% for obj in latest_posts|slice:"0:6" %}
                                            <a href="/posts/detail/{{obj.slug}}/" class="blog_cat">{{obj.title}}</a>
                                        <li>
                                               
                                            <a href="/posts/detail/{{obj.slug}}/">
                                                    {% if obj.image %}
                                                <img style="width:100%;" src="{{ obj.image.url }}" alt="">
                                                {% endif %}
                                               
                                            </a>
                                        </li>
                                        {% endfor %}
                                    
                                    </ul> 
                                    </div>
                            <!-- <div class="widget blog_gallery">
                                <h3>Our Gallery</h3>
                                <ul class="sidebar-gallery clearfix">
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-1.png' %}" alt="" /></a>
                                    </li>
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-2.png' %}" alt="" /></a>
                                    </li>
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-3.png' %}" alt="" /></a>
                                    </li>
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-4.png' %}" alt="" /></a>
                                    </li>
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-5.png' %}" alt="" /></a>
                                    </li>
                                    <li>
                                        <a href="#"><img src="{% static 'images/sidebar-g-6.png' %}" alt="" /></a>
                                    </li>
                                </ul>
                            </div> -->
                            <!--/.blog_gallery-->
                            
                            <!-- <div class="widget social_icon">
                                <a href="#" class="fa fa-facebook"></a>
                                <a href="#" class="fa fa-twitter"></a>
                                <a href="#" class="fa fa-linkedin"></a>
                                <a href="#" class="fa fa-pinterest"></a>
                                <a href="#" class="fa fa-github"></a>
                            </div> -->
                            
                        </aside>


                        
                    </div>
                    <!--/.row-->
                    <!-- <div class="row">
                        <div class="col-xs-12 text-center">
                            {% if object_list.has_other_pages %}
                            <ul class="pagination pagination-lg">
                                {% if object_list.has_previous %}
                              
                                <li><a href="?page={{object_list.previous_page_number}}" style="margin-left:0px;"><i style="margin-left:15px;" class="fa fa-long-arrow-left"></i></a></li>
                                {%else%}
                                <li class="disabled"><a href="#" style="margin-left:0;"><i style="margin-left:15px;"class="fa fa-long-arrow-left"></i></a></li>
                                {% endif %}

                                {% for i in object_list.paginator.page_range %}
                                {%if object_list.numbers == i %}
                                <li class="active"><a href="#">{{i}}</a></li>
                                {% else %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                                {% endif %}
                                {% endfor %}

                                {% if object_list.has_next %}
                              
                                <li><a href="?page={{object_list.next_page_number}}" style="margin-left:0;margin-right:15px;"><i class="fa fa-long-arrow-right"></i></a></li>
                                {%else%}
                                <li class="disabled"><a href="#" style="margin-left:0;margin-right:15px;"><i class="fa fa-long-arrow-right"></i></a></li>
                                {% endif %}
                             
                                <!-- <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#"><i class="fa fa-long-arrow-right"></i></a></li> -->
                            <!-- </ul> -->
                            {%endif %}
                            <!--/.pagination-->
                        <!-- </div> -->
                    <!-- </div> --> 
                </div>
            </section>
            <!--/#blog-->
        </div> 
        <div class="row contact-wrap"> 
        
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->


{% endblock %}