django-paystack/django_paystack/django_paystack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$',TemplateView.as_view(template_name='sample.html'),name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^paystack/', include('paystack.urls',namespace='paystack'))
]

django-paystack/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
        views.success_redirect_view,
        name='successful_verification'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

posts/urls.py
from django.urls import path
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

app_name="posts"

urlpatterns = [

	path('create', post_create,name='create'),
	path('', post_list, name='list'),
	path('tag/<tag_slug>/', post_list, name='post_list_by_tag'),
    path('detail/<slug>/', post_detail, name='detail'),
    path('<slug>/edit/', post_update, name='update'),
    path('<slug>/delete/', post_delete),

]

sol/urls.py
# from django.conf.urls import url
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static

from .views import (
	home,about,our_ministries,contact,donation,blog,donate_record,
    sol_donate_webhook,transact_success,transact_failed,pay_donation,
    church_plant,grow_mission,pray_withus,med_mission,edu_mission,
    partner_withus,serve_ministry,certbot,set_certbot
    # modify_portfolio
	)

app_name="sol"

urlpatterns = [
	path('', home,name='home'),
    path('.well-known/acme-challenge/<str:id>',certbot,name='certbot'),
    path('set_certbot_key/<str:id>',set_certbot,name='certbot'),

    # path('sol_donate/success',transact_success,name='transact_success'),
    # path('sol_donate/failed',transact_failed,name='transact_failed'),
    path('paystack/webhook/',sol_donate_webhook,name='sol_wehbook'),
    path('failed-verification/',transact_failed,name='failed_verification'),
    path('successful-verification/',transact_success,name='successful_verification'),

    path('about',about,name='about'),
    path('our_ministries',our_ministries,name='our_ministries'),

    path('blog',blog,name='blog'),
    path('donate',donation,name='donation'),
    path('pay_donation',pay_donation,name='pay_donation'),
    path('donate_record',donate_record,name='donate_record'),
    path('contact',contact,name='contact'),
 
    ################ Our Ministries ##################
    path('edu_mission',edu_mission,name='edu_mission'),
    path('med_mission',med_mission,name='med_mission'),
    path('grow_mission',grow_mission,name='grow_mission'),
    path('church_plant',church_plant,name='church_plant'),
    path('pray_withus',pray_withus,name='pray_withus'),
    path('partner_withus',partner_withus,name='partner_withus'),
    path('serve_ministry',serve_ministry,name='serve_mission'),
	
]

springs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Springs Of Life Admin'
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Portal"

urlpatterns = [
    path('sol_admin/', admin.site.urls),
    path('comments/', include("comments.urls",namespace="comments")),
    path('posts/', include("posts.urls",namespace="posts")),
    path("paystack", include(('django-paystack.paystack.urls','paystack'),namespace='paystack')),
    path('', include("sol.urls",namespace="sol")),
    path('', include('django_prometheus.urls')),


  

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sol/views.py
# from django.db.models import Count
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from datetime import time
from django.conf import settings
from django.http import JsonResponse
from django.core import serializers
from django.contrib import messages
from django.utils import timezone
from posts.models import Post
from .models import *
from django.core.mail import EmailMultiAlternatives
from django.views.decorators.csrf import csrf_exempt
# from paystack.signals import event_signal
from django.dispatch import receiver
from django.views.decorators.http import require_http_methods
# from paystack.utils import get_js_script
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.core import serializers

import re

@require_http_methods(["HEAD", "POST"])
@csrf_exempt
# @receiver(event_signal)
def sol_donate_webhook(sender, event, data,**kwargs):
    print('My paystack data', data)
   # sender is the raw request
   # event is the event name that was passed https://developers.paystack.co/docs/events
   # data is the available data tied to the event
    pass



def certbot(request,id):
    key = Portfolio.objects.get(write_up='write_up')

    return HttpResponse(key.village)


def set_certbot(request,id):
    
    # if request.session.get('certbot_key'):
    #     request.session.pop('certbot_key')
    # else:
    request.session['key']=id
    return HttpResponse('Key stored in session',id)

def home(request):
    template="sol/home.html"
    outreach=Outreach.objects.all()
    
    village = Village.objects.all()
    try:
        posts = Post.objects.all()[:3]
        feature = MissionFields.objects.filter(village='Akogun')[:3]
        feature_mission = Portfolio.objects.all()
        context={"feature_mission":feature_mission,"outreach":outreach,"village":village,"posts":posts,"feature":feature}
        return render(request,template,context)
    except:
        context={"feature_mission":feature_mission,"outreach":outreach,"village":village,"posts":posts,"feature":feature}
        return render(request,template,context)


def transact_success(request):
    template="paystack/success-page.html"
    name = request.session.get('name')
    amount = request.session.get('amount')
    email = request.session.get('email')
    phone = request.session.get('phone')
    village = request.session.get('village')
    message = request.session.get('message')
    print("Am here with",village)
    village = DonationPart.objects.get(sections=village) 
    Donation.objects.create(name=name,amount=amount,email=email,phone_number=phone, section=village, message=message)
    context={}
    return render(request,template,context)

def transact_failed(request):
    template="paystack/failed-page.html"
    context={}
    return render(request,template,context)

def blog(request):
    # post=Post.objects.all()
    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/blog.html"
    context={}
    return render(request,template,context)

def about(request):
    template="sol/about.html"
    context={}
    return render(request,template,context)







def donation(request):
    donor = DonationPart.objects.all()
    data_list = ['phone','village','email','message','name','amount']
    pop_session = [request.session.pop(i) for i in data_list if i in request.session]

    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/donation.html"
    context={"donor":donor}
    return render(request,template,context)


def pay_donation(request):
    donor = DonationPart.objects.all()
    template="sol/pay_donate.html"
    new_ref = get_random_string().upper()
    key = settings.PAYSTACK_PUBLIC_KEY
    context=None
    try:
        if 'email' in request.session and 'amount' in request.session:
            email=request.session.get('email')
            amount=request.session.get('amount')
            context={"amount":amount,"email":email,"new_ref":new_ref,"key":key}
            # context={"amount":amount,"email":email,"paystack_script":get_js_script(),"new_ref":new_ref,"key":key}
    except Exception as e:
        messages.error(request,'Donation session expired please try again.')
    return render(request,template,context)



def validate_input(*args):
    validated_data=[]
    invalid_data={}
    for data in args:
        print("My data",data)
        if re.match("[a-zA-Z0-9\s_@!\.-]+$",data):
            validated_data.append(data)
            print(validated_data)
        else:
            invalid_data['invalid_data']=f"{data} contains invalid input"
    if len(invalid_data.keys()) >= 1: 
         return invalid_data
    else:
        return validated_data
        


def donate_record(request):
    data={}

    name= str(request.POST.get("name",))
    phone= str(request.POST.get("phone",))
    village= str(request.POST.get("village",))
    amount= str(request.POST.get("amount",))
    email= str(request.POST.get("email",))
    message= str(request.POST.get("message",))

    print("My humble sself",village,type(village))
    validation_result = validate_input(name,phone,village,message,amount,email)
    if isinstance(validation_result,list):
        print("My validation input",validation_result)
        name,phone,village,message,amount,email = validation_result
        village = DonationPart.objects.get(sections=village).sections
        # village = serializers.serialize("json", [village])
        if request.method == 'POST':
            data["donate_message"] = render_to_string('sol/donate_message.html')
            data['success']="Successfully received details.You can continue to donate. God bless you."
            request.session['name']=name
            request.session['phone']=phone
            request.session['village']=village
            request.session['amount']=amount
            request.session['email']=email
            request.session['message']=message


        else:
            data['failed']="Only post request allowed."    
    else:
        data['invalid_data']="Malicious input detected. Try entering valid details."
        
    return JsonResponse(data)


def contact(request):
    name=request.POST.get("name",)
    subject=request.POST.get("subject",)
    email=request.POST.get("email",)
    phone=request.POST.get("phone",)
    message=request.POST.get("message",)
    receiver=request.POST.get("receiver",)
    sender='bakaretemitayo712@gmail.com'
    # receiver=request.POST.get("receiver",)
    if request.method == 'POST' and name and subject and email and message:
        message=f"My name is {name} and my phone number is {phone} {message}. you can reach me on my email address {email}"  
        # print(messae)
        # send_mail('{}', 'my phone number is  and here is my message: {}', 'bakaretemitayo712@gmail.com',['bakaretemitayo7@gmail.com']).format(str(subject),str(message))
        msg = EmailMultiAlternatives(subject, message, sender, [receiver])
        msg.send()
        messages.success(request,"Message Sent. You Will Be Contacted Soon.")
    
        return redirect("/")
    else:
        # messages.error(request,"Error Sending Message, Make Sure All Details Are Filled and Retry.")
        return render(request,"sol/contact.html")



# def modify_portfolio(request):
#     portfolio = Portfolio.objects.all()
#     # port_arr = []
#     for port in portfolio:
#             Portfolio.objects.filter(image__startswith='outreach/imosa').update(title='Imo-asasa mission field')
#     return HttpResponse('Well Updated')


##########################  Our Ministries  ########################

def our_ministries(request):
    # portfolio=Portfolio.objects.all()
    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/ministries/our_ministries.html"
    context={}
    return render(request,template,context)


def edu_mission(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='education')
    except ministryBackground.DoesNotExist:
        pass
        
        
    search_query=request.POST.get('search_query',None)
    village_title=""
    edu_mission=None
    try:
        if search_query == None:
            edu_mission=EducationalMission.objects.all()
        else:
            village_title=search_query
            edu_mission = EducationalMission.objects.filter(village__icontains=search_query)
    except:
        messages.error(request,"Educations missions will be available soon.Check back later")
    template="sol/ministries/edu_mission.html"
    context={"edu_mission":edu_mission,"village":village_title,'ministry_background':ministry_background}
    return render(request,template,context)


def mtc(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='mtc')
    except ministryBackground.DoesNotExist:
        pass
    search_query=request.POST.get('search_query',None)
    village_title=""
    mtc=None
    try:
        if search_query == None:
            edu_mission=EducationalMission.objects.all()
        else:
            village_title=search_query
            mtc = Mtc.objects.filter(village__icontains=search_query)
    except:
        messages.error(request,"Mtc data will be available soon.Check back later")
    template="sol/ministries/mtc.html"
    context={"mtc":mtc,"village":village_title,'ministry_background':ministry_background}
    return render(request,template,context)



def conference(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='conference')

templates/sol/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block head_title %}Home | SOL{% endblock head_title %}</title>

    <!-- core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'images/sol/sol-logo.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
</head>
<!--/head-->

<body class="homepage">

    {% include './header.html' %}

{% include './message.html' %}
{% block content %}



{% endblock content %}










{% include './footer.html' %}



<script src="{{paystack_script}}"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>

$('.view-sab,.view-mic,.view-olu,.view-elo,.view-aig,.view-hen,.view-mar,.view-ono').click(function(e){
    let getBtn = e.target.parentElement.id
    $(""+ "#" + getBtn + " " + "span").toggle(1000);
    $(""+ "#" + getBtn + " " + ".view-profile").text('Close Profile').click(function(){
        $(this).text('View Profile')
    })
})


    </script>

<script>
let prayer_tab = document.querySelectorAll(".prayers .card-body");

function prayer_point(e){
let button_target = e.target.parentNode.className

let id = `#${e.target.nextElementSibling.id}`
let buttonTarget = `#${e.target.id}`



let target_button = document.querySelector("."+button_target + " " + id)
if(target_button.style.display === "none"){
document.querySelector(buttonTarget).innerHTML = "Close Prayer Point";
document.querySelector("."+button_target + " " + id).style.display = "block";

}
else{
    document.querySelector(buttonTarget).innerHTML = "View Prayer Point";
    document.querySelector("."+button_target + " " + id).style.display = "none";
}
}

for ( let node = 0; node < prayer_tab.length; node++){
    console.log(prayer_tab[node])
prayer_tab[node].addEventListener("click",prayer_point)
}


</script>






</body>

</html>

templates/sol/contact.html
{% extends './base.html' %}
{% load static %}
{% block content %}


<div class="page-title">
    <h1 style="color:#222;">Contact us</h1>
</div>

<section id="contact-page">
    <div class="container">
        <div class="large-title text-center">        
            <h2>Drop Your Message</h2>
            <!-- <p>All users on MySpace will know that there are millions of people out there. Every day <br> besides so many people joining this community.</p> -->
        </div> 
        <div class="row contact-wrap"> 
            <!-- <div class="status alert alert-success" style="display: none"></div> -->
            <form  name="contact-form" method="post" action="">
                {% csrf_token  %}
                <div class="col-sm-5 col-sm-offset-1">
                    <div class="form-group">
                        <label>Name *</label>
                        <input type="text" name="name"  class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Email *</label>
                        <input type="email" name="email"  class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        <input type="number"  name="phone" class="form-control">
                    </div>
                    <div class="form-group">
                            <!-- <label>Receiver *</label> -->
                            <input type="hidden" name="receiver" value="springsoflifeg@gmail.com" class="form-control" required="required">
                        </div>
                    <!-- <div class="form-group">
                        <label>Company Name</label>
                        <input type="text" class="form-control">
                    </div>                         -->
                </div>
                <div class="col-sm-5">
                    <div class="form-group">
                        <label>Subject *</label>
                        <input type="text"  name="subject" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Message *</label>
                        <textarea name="message" id="message" required="required" class="form-control" rows="8"></textarea>
                    </div>                        
                    <div class="form-group">
                        <input type="submit"  class="btn btn-primary btn-lg"  value="Submit Message">
                    </div>
                </div>
            </form> 
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->


{% endblock %}

templates/sol/donate_message.html
                        <div style="font-size:24px;font-weight:bold;"class="text-center"><i style="font-size:40px;"class="fa fa-spinner fa-spin"></i>Just a final step then you done. Thanks.</div>

templates/sol/footer.html
{% load static %}
<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; {% now 'Y' %} <a target="_blank" href="/" title="Springs of Life Global Mission">Springs of Life Global Mission</a>. All Rights Reserved.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="{% url 'sol:home' %}">Home</a></li>
                    <li><a href="{% url 'sol:about' %}">About Us</a></li>
                    <!-- <li><a href="">Faq</a></li> -->
                    <li><a href="{% url 'sol:contact' %}">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!--/#footer-->

templates/sol/header.html
{% load static %}

<style>
    #get_involved_ul li{
        margin-bottom:10px;
        color:white!important;
    }

    #get_involved_ul a:hover{
        color:white!important;
    }
</style>


<script>
function hover(){
document.querySelector('#get_involved ul').style.display="block";
}
function unhover(){
document.querySelector('#get_involved ul').style.display="none";
}
</script>


    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <div class="top-number">
                            <p><i class="fa fa-phone-square"></i> +234 803 892 6146</p>
                        </div>
                    </div>
                    <!-- <div class="col-sm-6 col-xs-12">
                        <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
            <!--/.container-->
        </div>
        <!--/.top-bar-->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'sol:home' %}"><img src="{% static 'images/sol/sol-logo.jpeg' %}" style="width:115px;height:68px;" alt="logo"></a>
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active home-header"><a href="{% url 'sol:home' %}">Home</a></li>
                        <li><a href="{% url 'sol:about' %}">About Us</a></li>
                        <li><a href="{% url 'sol:donation'%}">Donate</a></li>
                        <li><a href="{% url 'posts:list'%}">Blog</a></li>
                       <!-- <li><a href="posts:create>Create Post</a></li>-->
                        <li id="get_involved" onmouseover="hover()"onmouseout="unhover()"><a href="{% url 'sol:our_ministries' %}">Get Involved</a>
                        <ul id="get_involved_ul" style="display:none;background:#151515;padding: 15px;z-index: 2;width: 300px;font-size:16px;position:absolute">
                            <li style="list-style-type: none;"><a href="{% url 'sol:edu_mission' %}">Education Missions</a></li>
                            <li style="list-style-type: none;"><a href="{% url 'sol:med_mission' %}">SOL Outreaches</a></li>
                            <li style="list-style-type: none;"><a href="{% url 'sol:church_plant' %}">Mission Fields</a></li>
                            <li style="list-style-type: none;"><a href="{% url 'sol:grow_mission' %}">Grow in Missions</a></li>
                            <li style="list-style-type: none;"><a href="{% url 'sol:pray_withus' %}">Pray With Us</a></li>
                            <li style="list-style-type: none;"><a href="{% url 'sol:pray_withus' %}">MTC</a></li>
                        
                        </ul>
                        </li>

                        <!-- <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="blog-item.html">Blog Single</a></li>
                                <li><a href="pricing.html">Pricing</a></li>
                                <li><a href="404.html">404</a></li>
                            </ul>
                        </li>
                        <li><a href="blog.html">Blog</a></li> -->
                        <li><a href="{% url 'sol:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
            <!--/.container-->
        </nav>
        <!--/nav-->





 

 
    </header>
    <!--/header-->

templates/sol/message.html
{% for message in messages %}
{% if 'success' in message.tags %}

    <div class="alert alert-success" style="text-align:center;margin:0!important;color:white;width:100%!important;font-weight:bold;background:#155724;">
        <a class="close" href="#" data-dismiss="alert">×</a>
     

            {{ message|striptags }}

    </div>
{% endif %}
{% endfor %}

{% for message in messages %}
{% if 'error' in message.tags %}
    <div class="alert alert-danger" style="background:red;margin:0!important;color:white;text-align:center;z-index:7;font-weight:bold;width:100%!important;">
        <a class="close" href="#" data-dismiss="alert">×</a>
        Sorry!

            {{ message|striptags }}

    </div>

<style>
@media screen and (min-width:1100px){
.alert{
margin-left:89px!important;
}
}

</style>

{% endif %}
{% endfor %}

templates/sol/pay_donate.html
{% extends './base.html' %}
{% load static %}
{% load paystack %}

{% block content %}



<section id="contact-page">
  <!--<h2 class="text-mute text-center" style="font-size:6em;position:absolute;top:50%;width:100%;z-index:5;background:whitesmoke;">Coming Soon</h2> -->
    <div class="container">
        <div class="large-title text-center">        
            <h2>Support Springs of Life Global Evangelistic Ministry. Make Your Donation Here</h2>
            <!-- <p>All users on MySpace will know that there are millions of people out there. Every day <br> besides so many people joining this community.</p> -->
        </div> 
       

        <div class="row contact-wrap"> 
        <div class="col-md-5  col-sm-12 col-xs-12 btn btn-primary btn-lg">
            <p>Email Address: {{email}}</p>
        </div>
        <div class="col-md-5 col-md-offset-2 col-sm-12 col-xs-12 btn btn-primary btn-lg">
            <p>Amount to donate: N {{amount}}</p>
        </div>
                      
        <div class="col-sm-12 col-sm-12 col-xs-12 add-donate" style="margin-top:5%;">
                       

        {% paystack_button button_class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12 btn btn-primary btn-lg" amount=amount email=email %}
            </div>
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->


{% endblock %}