django-paystack/django_paystack/django_paystack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$',TemplateView.as_view(template_name='sample.html'),name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^paystack/', include('paystack.urls',namespace='paystack'))
]

django-paystack/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
        views.success_redirect_view,
        name='successful_verification'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

sol/urls.py
# from django.conf.urls import url
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static

from .views import (
	home,about,our_ministries,contact,donation,blog,donate_record,
    sol_donate_webhook,transact_success,transact_failed,pay_donation,
    church_plant,grow_mission,pray_withus,med_mission,edu_mission,
    partner_withus,serve_ministry,certbot,set_certbot
    # modify_portfolio
	)

app_name="sol"

urlpatterns = [
	path('', home,name='home'),
    path('.well-known/acme-challenge/<str:id>',certbot,name='certbot'),
    path('set_certbot_key/<str:id>',set_certbot,name='certbot'),

    # path('sol_donate/success',transact_success,name='transact_success'),
    # path('sol_donate/failed',transact_failed,name='transact_failed'),
    path('paystack/webhook/',sol_donate_webhook,name='sol_wehbook'),
    path('failed-verification/',transact_failed,name='failed_verification'),
    path('successful-verification/',transact_success,name='successful_verification'),

    path('about',about,name='about'),
    path('our_ministries',our_ministries,name='our_ministries'),

    path('blog',blog,name='blog'),
    path('donate',donation,name='donation'),
    path('pay_donation',pay_donation,name='pay_donation'),
    path('donate_record',donate_record,name='donate_record'),
    path('contact',contact,name='contact'),
 
    ################ Our Ministries ##################
    path('edu_mission',edu_mission,name='edu_mission'),
    path('med_mission',med_mission,name='med_mission'),
    path('grow_mission',grow_mission,name='grow_mission'),
    path('church_plant',church_plant,name='church_plant'),
    path('pray_withus',pray_withus,name='pray_withus'),
    path('partner_withus',partner_withus,name='partner_withus'),
    path('serve_ministry',serve_ministry,name='serve_mission'),
	
]

springs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Springs Of Life Admin'
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Portal"

urlpatterns = [
    path('sol_admin/', admin.site.urls),
    path('comments/', include("comments.urls",namespace="comments")),
    path('posts/', include("posts.urls",namespace="posts")),
    path("paystack", include(('django-paystack.paystack.urls','paystack'),namespace='paystack')),
    path('', include("sol.urls",namespace="sol")),
    path('', include('django_prometheus.urls')),


  

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sol/views.py
# from django.db.models import Count
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from datetime import time
from django.conf import settings
from django.http import JsonResponse
from django.core import serializers
from django.contrib import messages
from django.utils import timezone
from posts.models import Post
from .models import *
from django.core.mail import EmailMultiAlternatives
from django.views.decorators.csrf import csrf_exempt
# from paystack.signals import event_signal
from django.dispatch import receiver
from django.views.decorators.http import require_http_methods
# from paystack.utils import get_js_script
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.core import serializers

import re

@require_http_methods(["HEAD", "POST"])
@csrf_exempt
# @receiver(event_signal)
def sol_donate_webhook(sender, event, data,**kwargs):
    print('My paystack data', data)
   # sender is the raw request
   # event is the event name that was passed https://developers.paystack.co/docs/events
   # data is the available data tied to the event
    pass



def certbot(request,id):
    key = Portfolio.objects.get(write_up='write_up')

    return HttpResponse(key.village)


def set_certbot(request,id):
    
    # if request.session.get('certbot_key'):
    #     request.session.pop('certbot_key')
    # else:
    request.session['key']=id
    return HttpResponse('Key stored in session',id)

def home(request):
    template="sol/home.html"
    outreach=Outreach.objects.all()
    
    village = Village.objects.all()
    try:
        posts = Post.objects.all()[:3]
        feature = MissionFields.objects.filter(village='Akogun')[:3]
        feature_mission = Portfolio.objects.all()
        context={"feature_mission":feature_mission,"outreach":outreach,"village":village,"posts":posts,"feature":feature}
        return render(request,template,context)
    except:
        context={"feature_mission":feature_mission,"outreach":outreach,"village":village,"posts":posts,"feature":feature}
        return render(request,template,context)


def transact_success(request):
    template="paystack/success-page.html"
    name = request.session.get('name')
    amount = request.session.get('amount')
    email = request.session.get('email')
    phone = request.session.get('phone')
    village = request.session.get('village')
    message = request.session.get('message')
    print("Am here with",village)
    village = DonationPart.objects.get(sections=village) 
    Donation.objects.create(name=name,amount=amount,email=email,phone_number=phone, section=village, message=message)
    context={}
    return render(request,template,context)

def transact_failed(request):
    template="paystack/failed-page.html"
    context={}
    return render(request,template,context)

def blog(request):
    # post=Post.objects.all()
    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/blog.html"
    context={}
    return render(request,template,context)

def about(request):
    template="sol/about.html"
    context={}
    return render(request,template,context)







def donation(request):
    donor = DonationPart.objects.all()
    data_list = ['phone','village','email','message','name','amount']
    pop_session = [request.session.pop(i) for i in data_list if i in request.session]

    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/donation.html"
    context={"donor":donor}
    return render(request,template,context)


def pay_donation(request):
    donor = DonationPart.objects.all()
    template="sol/pay_donate.html"
    new_ref = get_random_string().upper()
    key = settings.PAYSTACK_PUBLIC_KEY
    context=None
    try:
        if 'email' in request.session and 'amount' in request.session:
            email=request.session.get('email')
            amount=request.session.get('amount')
            context={"amount":amount,"email":email,"new_ref":new_ref,"key":key}
            # context={"amount":amount,"email":email,"paystack_script":get_js_script(),"new_ref":new_ref,"key":key}
    except Exception as e:
        messages.error(request,'Donation session expired please try again.')
    return render(request,template,context)



def validate_input(*args):
    validated_data=[]
    invalid_data={}
    for data in args:
        print("My data",data)
        if re.match("[a-zA-Z0-9\s_@!\.-]+$",data):
            validated_data.append(data)
            print(validated_data)
        else:
            invalid_data['invalid_data']=f"{data} contains invalid input"
    if len(invalid_data.keys()) >= 1: 
         return invalid_data
    else:
        return validated_data
        


def donate_record(request):
    data={}

    name= str(request.POST.get("name",))
    phone= str(request.POST.get("phone",))
    village= str(request.POST.get("village",))
    amount= str(request.POST.get("amount",))
    email= str(request.POST.get("email",))
    message= str(request.POST.get("message",))

    print("My humble sself",village,type(village))
    validation_result = validate_input(name,phone,village,message,amount,email)
    if isinstance(validation_result,list):
        print("My validation input",validation_result)
        name,phone,village,message,amount,email = validation_result
        village = DonationPart.objects.get(sections=village).sections
        # village = serializers.serialize("json", [village])
        if request.method == 'POST':
            data["donate_message"] = render_to_string('sol/donate_message.html')
            data['success']="Successfully received details.You can continue to donate. God bless you."
            request.session['name']=name
            request.session['phone']=phone
            request.session['village']=village
            request.session['amount']=amount
            request.session['email']=email
            request.session['message']=message


        else:
            data['failed']="Only post request allowed."    
    else:
        data['invalid_data']="Malicious input detected. Try entering valid details."
        
    return JsonResponse(data)


def contact(request):
    name=request.POST.get("name",)
    subject=request.POST.get("subject",)
    email=request.POST.get("email",)
    phone=request.POST.get("phone",)
    message=request.POST.get("message",)
    receiver=request.POST.get("receiver",)
    sender='bakaretemitayo712@gmail.com'
    # receiver=request.POST.get("receiver",)
    if request.method == 'POST' and name and subject and email and message:
        message=f"My name is {name} and my phone number is {phone} {message}. you can reach me on my email address {email}"  
        # print(messae)
        # send_mail('{}', 'my phone number is  and here is my message: {}', 'bakaretemitayo712@gmail.com',['bakaretemitayo7@gmail.com']).format(str(subject),str(message))
        msg = EmailMultiAlternatives(subject, message, sender, [receiver])
        msg.send()
        messages.success(request,"Message Sent. You Will Be Contacted Soon.")
    
        return redirect("/")
    else:
        # messages.error(request,"Error Sending Message, Make Sure All Details Are Filled and Retry.")
        return render(request,"sol/contact.html")



# def modify_portfolio(request):
#     portfolio = Portfolio.objects.all()
#     # port_arr = []
#     for port in portfolio:
#             Portfolio.objects.filter(image__startswith='outreach/imosa').update(title='Imo-asasa mission field')
#     return HttpResponse('Well Updated')


##########################  Our Ministries  ########################

def our_ministries(request):
    # portfolio=Portfolio.objects.all()
    # portfolio=Portfolio.objects.order_by().values_list("title",flat=True).distinct()
    template="sol/ministries/our_ministries.html"
    context={}
    return render(request,template,context)


def edu_mission(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='education')
    except ministryBackground.DoesNotExist:
        pass
        
        
    search_query=request.POST.get('search_query',None)
    village_title=""
    edu_mission=None
    try:
        if search_query == None:
            edu_mission=EducationalMission.objects.all()
        else:
            village_title=search_query
            edu_mission = EducationalMission.objects.filter(village__icontains=search_query)
    except:
        messages.error(request,"Educations missions will be available soon.Check back later")
    template="sol/ministries/edu_mission.html"
    context={"edu_mission":edu_mission,"village":village_title,'ministry_background':ministry_background}
    return render(request,template,context)


def mtc(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='mtc')
    except ministryBackground.DoesNotExist:
        pass
    search_query=request.POST.get('search_query',None)
    village_title=""
    mtc=None
    try:
        if search_query == None:
            edu_mission=EducationalMission.objects.all()
        else:
            village_title=search_query
            mtc = Mtc.objects.filter(village__icontains=search_query)
    except:
        messages.error(request,"Mtc data will be available soon.Check back later")
    template="sol/ministries/mtc.html"
    context={"mtc":mtc,"village":village_title,'ministry_background':ministry_background}
    return render(request,template,context)



def conference(request):
    ministry_background = None
    try:
        ministry_background = ministryBackground.objects.get(ministry_name='conference')

templates/sol/ministries/church_plant.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<style>
.search-title{
display:flex;
flex-direction:column;
}

.search-title form{
align-self:flex-end;
display:flex;
}


.search-title form button{
background:#EC5538;
color:white;
}

.search-title form button:hover{
background:#4e4e4e;
color:white;
}

.card{
height:auto;
padding:0px;
margin-bottom: 5%;
border: 2px solid whitesmoke;
box-shadow: -1px 6px 7px -4px;
}

.card img {
    height: 310px;
    width:100%;

  }

.ministry-wrapper{
    display:flex;
    flex-direction:column;

}

.ministry-header{
    padding:0;
}
.ministry-header .ministry-background{
height: 700px;
width:100%;
background-size:unset!important;

}

.img-background{
    position:absolute;
    top:600px;
    width:100%;
    
}
.img-background h1{
color:white;
}



@media only screen and (max-width: 600px) {
  .card img {
    height: 180px;
  }
.ministry-header .ministry-background{
height: 400px;
width:100%;
background-size:cover;

}
}
</style>
<section>
  
    <div class="container">
            <div class="ministry-wrapper">
<div class="col-md-12 ministry-header">
    {% if ministry_background %}
    <div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),
    url({{ministry_background.image.url}} );" ></div>
    {% else %}
<div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),url({% static 'images/sol/ministry/plant_ministry.jpeg'%})" ></div>
{% endif %}
<div class="img-background">
<h1>Mission Fields</h1>
 <hr>
 </div>
  <h2 class="text-center">If you want to stop the gates of hell in a place plant a church.</h2>
 <p>SOL believes that Jesus builds His Church(Mathew16:18) as missionaries and believers alike engage in discipleship. SOL missionaries use every means; one-on-one evangelism, open air crusades and events to engage communities with the gospel. As people come to Christ they are discipled to grow in their faith and develop to leaders of new faith communities. </p>
 


    </div>
        <div class="large-title text-center search-title">        
            
    <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <input class="form-control mr-sm-2" name="search_query" type="text" placeholder="Mission Fields">
    <button class="btn" type="submit" >Search</button>
    
  </form>
        </div> 
    <h2 class="text-center" style="font-weight:bold;">{{village}}</h2>     

        <div class="row"> 
{% for church in church_plant %}
      <div class="card col-md-4">
        
    <h2 class="text-center"><a href="/church_plant" class="blog_cat">{{church.village}} {{church.title}}</a></h2>
        
  <img class="card-img-top"  src="{{church.image.url}}" alt="Card image">
  <div class="card-body">
      {{church.write_up}}
  </div>
</div> 
{% empty %}
<h2 class="text-center">No data available for that village. Check back later.</h2>
{% endfor %}
</div> <!-- End Row -->
</div> <!-- End Ministry Wrapper -->
</div> <!-- End Container -->
</div> <!-- End Section -->
{% endblock content %}

templates/sol/ministries/conference.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<style>
.search-title{
display:flex;
flex-direction:column;
}

.search-title form{
align-self:flex-end;
display:flex;
}


.search-title form button{
background:#EC5538;
color:white;
}

.search-title form button:hover{
background:#4e4e4e;
color:white;
}

.card{
height:356px;
margin-bottom: 5%;
border: 2px solid whitesmoke;
box-shadow: -1px 6px 7px -4px;
}

.card img {
    height: 310px;
    width:100%;

  }

.ministry-wrapper{
    display:flex;
    flex-direction:column;

}

.ministry-header{
    padding:0;
}
.ministry-header .ministry-background{
height: 700px;
width:100%;
background-size:cover;

}

.img-background{
    position:absolute;
    top:600px;
    width:100%;
    
}
.img-background h1{
color:white;
}

@media only screen and (max-width: 600px) {
  .card img {
    height: 180px;
  }

  .ministry-header .ministry-background{
height: 400px;
width:100%;
background-size:cover;

}
}
</style>
<section>
  
    <div class="container">
            <div class="ministry-wrapper">
<div class="col-md-12 ministry-header">
    {% if ministry_background %}
    <div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),
    url({{ministry_background.image.url}} ); background-position:center;" ></div>
    {% else %}
<div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),url({% static 'images/sol/ministry/plant_ministry.jpeg'%})" ></div>
{%endif%}
<div class="img-background">
<h1>Conference and Programs</h1>
 <hr>
 </div>
  <h2 class="text-center">If you want to stop the gates of hell in a place.Plant a church.</h2>
 <p>SOL believes that Jesus builds His church(mathew16:18) as believers engage in discipleship. SOL missionaries use one-on-one evangelism, public meetings and events to engage communities with the gospel. As people come to Christ they are discipled to grow in their faith and develop to leaders of new faith communities. </p>
 


    </div>
        <div class="large-title text-center search-title">        
            
    <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <input class="form-control mr-sm-2" name="search_query" type="text" placeholder="Search">
    <button class="btn" type="submit" >Search</button>
    
  </form>
        </div> 
    <h2 class="text-center" style="font-weight:bold;">{{village}}</h2>     

        <div class="row"> 
{% for conference in conference %}
      <div class="card col-md-4">
  <img class="card-img-top" src="{{conference.link}}" alt="Card image">
  <div class="card-body">
  </div>
</div> 
{% empty %}
<h2 class="text-center">No data available for that village. Check back later.</h2>
{% endfor %}
</div> <!-- End Row -->
</div> <!-- End Ministry Wrapper -->
</div> <!-- End Container -->
</div> <!-- End Section -->
{% endblock content %}

templates/sol/ministries/edu_mission.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<style>
.search-title{
display:flex;
flex-direction:column;
}

.search-title form{
align-self:flex-end;
display:flex;
}


.search-title form button{
background:#EC5538;
color:white;
}

.search-title form button:hover{
background:#4e4e4e;
color:white;
}


.card{
height:auto;
margin-bottom: 5%;
border: 2px solid whitesmoke;
box-shadow: -1px 6px 7px -4px;
}

.card img {
    height: 310px;
    width:100%;

  }

.ministry-wrapper{
    display:flex;
    flex-direction:column;

}

.ministry-header{
    padding:0;
}
.ministry-header .ministry-background{
height: 700px;
width:100%;

}

.img-background{
    position:absolute;
    top:600px;
    width:100%;
    
}
.img-background h1{
color:white;
}

@media only screen and (max-width: 600px) {
  .card img {
    height: 180px;
  }

  .ministry-header .ministry-background{
height: 400px;
width:100%;
background-size:cover;

}
}
</style>
<section>


    <div class="container">
    <div class="ministry-wrapper">
<div class="col-md-12 ministry-header">
    {% if ministry_background %}
<div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),
url({{ministry_background.image.url}} ); background-position:center;" ></div>
{% else %}
<div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),
url({% static 'images/sol/ministry/edu_ministry.jpeg'%} )" ></div>
{% endif %}
<div class="img-background">
 <h1>Educational Missions</h1>
 <hr>
 </div>
 <h2 class="text-center">Access to education changes lives now and for generations to come. This is a long-term suitable impact.</h2>
 <p>When communities are poverty stricken, in the short term it will be necessary to meet people's immediate needs in the form of food, shelter and clothes. SOL does all of these, but our goal is always long term-missions that transforms and restores. We believe one of the most strategic ways to bring about transformation of communities in the long term is through education. We establish tuition free schools where none exists. </p>
    </div>


<div class="large-title text-center search-title">                   
    <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <input class="form-control mr-sm-2" name="search_query" type="text" placeholder="Search by village">
    <button class="btn" type="submit">Search</button>
  </form>
  <h2 class="text-center" style="font-weight:bold;">{{village}}</h2>
        </div> 
         

<div class="row"> 
{% for edu in edu_mission %}
      <div class="card col-md-4">
        <h2 class="text-center">  {{edu.title}}({{edu.village}})</h2>

  <img class="card-img-top" src="{{edu.image.url}}" alt="Card image">
  <div class="card-body">
      {{edu.write_up}}
  </div>
</div> 
{% empty %}
<h2 class="text-center">No data available for that village. Check back later.</h2>
{% endfor %}
</div> <!-- End Row -->
</div><!-- End Ministry Wrapper -->
</div> <!-- End Container -->
</div> <!-- End Section -->
{% endblock content %}

templates/sol/ministries/grow_mission.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<style>
.search-title{
display:flex;
flex-direction:column;
}

.search-title form{
align-self:flex-end;
display:flex;
}


.search-title form button{
background:#EC5538;
color:white;
}

.search-title form button:hover{
background:#4e4e4e;
color:white;
}

.card{
margin-bottom: 5%;
border: 2px solid whitesmoke;
box-shadow: -1px 6px 7px -4px;
}

.card img {
    height: 310px;
    width:100%;

  }

.ministry-wrapper{
    display:flex;
    flex-direction:column;

}

.ministry-header{
    padding:0;
}
.ministry-header .ministry-background{
height: 700px;
width:100%;
background-size:cover;

}

.img-background{
    position:absolute;
    top:600px;
    width:100%;
    
}
.img-background h1{
color:white;
}

@media only screen and (max-width: 600px) {
  .card img {
    height: 180px;
  }

  .ministry-header .ministry-background{
height: 400px;
width:100%;
background-size:cover;

}
}
</style>
<section>
  
    <div class="container">
            <div class="ministry-wrapper">
<div class="col-md-12 ministry-header">
  {% if ministry_background %}
  <div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),
  url({{ministry_background.image.url}} ); background-position:center;" ></div>
  {% else %}
<div class="ministry-background" style="background-image:linear-gradient(rgba(0, 0, 0, 0.3)100%,rgba(0,0,0,0.5)100%),url({% static 'images/sol/ministry/grow_ministry.jpg'%})" ></div>
{% endif %}
<div class="img-background">
<h1>Grow Your Minds In God's Mission Through 5 Minutes Videos</h1>
 <hr>
 </div>
 
 
    </div>
        
    <h2 class="text-center" style="font-weight:bold;">{{village}}</h2>     

        <div class="row"> 
{% for grow in grow_mission %}
<div class="card col-md-4">
<h2 class="text-center">{{grow.title}}</h2>
  <video style="width:100%;" class="card-img-top" controls>
  <source src="{{grow.link}}" type="video/mp4">
  <source src="{{grow.link}}" type="video/ogg">
  Your browser does not support the video tag.
</video>
  <div class="card-body">
  </div>
</div> 
{%empty%}
<p class="text-center">No villages available yet. Kindly check back later.</p>
{% endfor %}

</div> <!-- End Row -->
</div> <!-- End Ministry Wrapper -->
</div> <!-- End Container -->
</section> <!-- End Section -->
{% endblock content %}

templates/sol/ministries/our_ministries.html
{% extends '../base.html' %}
{% load static %}

{% block content %}

<style>
.card{

margin-bottom: 5%;
border: 2px solid whitesmoke;
box-shadow: -1px 6px 7px -4px;
}

.card img{
height: 310px;
width:100%;
margin-bottom: 5%;
}

.card a{
    cursor:pointer;
}

.card-body{
display: flex;
flex-direction: column;
align-self: center;
}


@media only screen and (max-width: 600px) {
  .card img {
    height: 180px;
  }
}
</style>
<section >
  
    <div class="container">
        <div class="large-title text-center">        
            <h2>Our Ministries</h2>
        </div> 
       





        <div class="row"> 

      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/edu_ministry.jpeg'%}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Educational Missions</h4>
    <a href="{% url 'sol:edu_mission' %}" class="btn btn-primary">See More</a>
  </div>
</div> 


      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/med_ministry.jpeg'%}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">SOL Outreaches</h4>
    <a href="{% url 'sol:med_mission' %}" class="btn btn-primary">See More</a>
  </div>
</div>


     <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/plant_ministry.jpeg'%}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Mission Fields</h4>
    <a href="{% url 'sol:church_plant' %}" class="btn btn-primary">See More</a>
  </div>
</div>


      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/grow_ministry.jpg'%}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Missions and You</h4>
    <a href="{% url 'sol:grow_mission' %}" class="btn btn-primary">See More</a>
  </div>
</div>




      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/pray_ministry.jpeg' %}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Pray With Us</h4>
    <a href="{% url 'sol:pray_withus' %}" class="btn btn-primary">See More</a>
  </div>
</div>



      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/partner_ministry.jpeg' %}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Partner With Us</h4>
    <a href="{% url 'sol:partner_withus' %}" class="btn btn-primary">See More</a>
  </div>
</div>



      <div class="card col-md-4">
  <img class="card-img-top" src="{% static 'images/sol/ministry/serve_ministry.jpeg' %}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title text-center">Serve</h4>
    <a href="{% url 'sol:serve_mission' %}" class="btn btn-primary">See More</a>
  </div>
</div>


        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->


{% endblock %}